### ISSUE TITLE
Feat: Manual testing of My Partners feature

### ISSUE THREAD

**Issue by yatharthmago01** [Code-Sauce-Official/FitMate#14] opened 2021-06-07 13:27 UTC
**What is your issue related to ?**

- [ ] Code
- [ ] Designing
- [x] Documentation
- [x] Testing/Research
- [ ] Others[please specify]

**Description**
Download the apk[[release version](https://github.com/Code-Sauce-Official/FitMate/releases/tag/1.0)] and test all different scenarios for the My Partners feature.

An md file with all the test scenarios you covered. Positive and negative test cases as expected. Each test scenario should be documented as below:
```
### Test1 : Description
**_Screenshot/gif_**<br>
<img src="Link" width="300"/><br>
**_Expected Result_**: <br>
**_Actual Result_**: <br>

### Test2 : Description
**_Screenshot/gif_**<br>
<img src="Link" width="300"/><br>
**_Expected Result_**: <br>
**_Actual Result_**: <br>

and so on
...

```
**Additional context**
Add you markdown(md) file in [Testing folder](https://github.com/Code-Sauce-Official/FitMate/tree/develop/Documentation/Testing)
If you see issues or unexpected behaviour during testing feel free to open an issue

**Comment by remote007** [comment] 2021-06-10 07:56
I'd like to work on this issue under LGMSOC'21 label.

**Comment by nidhisingh-1** [comment] 2021-06-10 09:46
Okay,  assigning this issue to you @PadminiRai

**Comment by remote007** [comment] 2021-06-11 12:54
@nidhisingh-1 could you please assign this issue under the **label :  LGMSOC'21**

**Comment by SHITIZ-AGGARWAL** [comment] 2021-06-15 12:48
@PadminiRai Update

**Comment by remote007** [comment] 2021-06-20 04:22
@SHITIZ-AGGARWAL am searching for different parameters that can be tested and compiling the pointers together

**Comment by remote007** [comment] 2021-06-20 04:26
@nidhisingh-1 @SHITIZ-AGGARWAL Also I observed a few pointer for other features like opening page, sign-in and warnings along with My Partners feature. So, if you open similar issues for these I'll specifically work on them as well and share my insights.

**Comment by yatharthmago01** [comment] 2021-06-20 04:50
@PadminiRai issues have been created for other pages of the application also. Some are still active and some have been closed. If you don't find an issue in either category, feel free to create one and we'll assign the same to you.

**Comment by yatharthmago01** [comment] 2021-06-20 04:51
And if you're on the brim about anything, feel free to share it with us first before opening an issue. Thanks!

**Comment by remote007** [comment] 2021-06-20 05:41
Can someone help me with workflow of the feature . To find a partner it asks to create a post.  Where will that post appear? also no possible matches appeared for the activity described in the post .

**Comment by yatharthmago01** [comment] 2021-06-20 05:44
@PadminiRai so first of all when you create a post, you make yourself available in that particular category. What you can do is use 2-3 ids of your own to match. When you click on Find partners, it first takes you to your created posts, and on clicking on any of the posts, you can find the possible matches.

**Comment by yatharthmago01** [comment] 2021-06-20 05:46
I hope this makes it somewhat clear to you. Else ping us and join the voice channel, and any one of us will explain the same to you in detail.

**Comment by remote007** [comment] 2021-06-20 05:48
@yatharthmago01 Got it , I'm on it . Thanks for the insight.

**Comment by remote007** [comment] 2021-06-20 07:51
![WhatsApp Image 2021-06-20 at 13 17 56](https://user-images.githubusercontent.com/59466080/122666307-16bcc100-d1ca-11eb-9c0e-387204ad8498.jpeg)
I created accounts using two ids and found out that the posts created from both accounts in badminton category do not appear anywhere and no possible matches are suggested. Should  I add it in my review of the feature.

**Comment by Acash512** [comment] 2021-06-20 09:38
It's not a bug, I just checked you have entered different states, for both accounts, UP for one and Goa for another, the app matches people having same state, category and age difference of 3 years taking care of their gender preference. Since the edit profile feature is yet to be implemented, you can either create a different account with same state or I can change your state directy from the Firebase console, whichever suits you. You also need an age difference of 3 yrs at most so keep that in mind as well.

**Comment by remote007** [comment] 2021-06-20 09:49
Thanks @Acash512. I've created a new account but if you could change the state from Goa to UP I'll be able to test the feature with 3 ids.

**Comment by Acash512** [comment] 2021-06-20 09:52
Done, I have changed your state to Uttar Pradesh and year of birth to 2001 for that id.

**Comment by remote007** [comment] 2021-06-23 02:58
@Acash512 @SHITIZ-AGGARWAL @nidhisingh-1 @yatharthmago01 
Thanks for sharing the insights . I've create the **PR** : https://github.com/Code-Sauce-Official/FitMate/pull/60

**Closed as completed** 2021-06-25 09:36 UTC
Labels: documentation, good first issue, testing, Level2, LGMSOC21
